device: '3'
experiment_name: codex_teacher_pass20_student_125M_pass10_temp0.1
inference_batch_size: 25
max_new_tokens: 200
model_path: train_results/codex_teacher_pass20_125M_student/checkpoint-19850
num_samples: 10
param_count: 125M
prompt_length: 200
temp: 0.1
