device: '1'
experiment_name: codex_teacher_pass20_student_1B_pass10_temp0.2
inference_batch_size: 12
max_new_tokens: 200
model_path: train_results/codex_teacher_pass20_1-3B_student/checkpoint-39700/
num_samples: 10
param_count: 1.3B
prompt_length: 200
temp: 0.2
