batch_size: 8
devices: '0'
epochs: 140
eval_batch_size: 1
experiment_name: gptj_teacher_pass100_gptneo1B_student_validation_pass_1_standard_params
gradient_accumulation_steps: 4
lr: 0.0001
max_gen_tokens: 150
max_length: 400
model_name: EleutherAI/gpt-neo-1.3B
model_type: gptneo
num_samples: 1
teacher_data_path: ../few_shot/results/gpt-j-full-pass100.json
temp: 0
train_on_dev: false
weight_decay: 0.1
