batch_size: 8
devices: '1'
do_train: false
epochs: 140
eval_batch_size: 1
experiment_name: gptneo2B_teacher_pass100_gptneo125M_student_kd_test_100
gradient_accumulation_steps: 4
lr: 0.0001
max_gen_tokens: 150
max_length: 400
model_name: EleutherAI/gpt-neo-125M
model_path: /data/lily/nos6/etknew/ETK/etk/knowledge_distillation/distill_train_results/KD_2B_teacher_pass100_gptneo125M_student_with_validation_new_hparams/checkpoint-5590/
model_type: gptneo
num_samples: 100
teacher_data_path: ../few_shot/results/codex_gsm8k_full_pass100.json
temp: 0.6
train_on_dev: false
weight_decay: 0.1
