batch_size: 8
devices: '1'
epochs: 50
experiment_name: codex_teacher_pass20_incoder1B_student
lr: 2.0e-05
max_length: 400
model_name: facebook/incoder-1B
teacher_data_path: ../few_shot/results/codex_gsm8k_full_pass20.json
weight_decay: 0.01
