experiment_name: codex_teacher_pass20_student_125M_pass10_temp0.3
device: "2"
inference_batch_size: 25
max_new_tokens: 200
num_samples: 10
temp: 0.3
prompt_length: 200
model_path: "train_results/codex_teacher_pass20_125M_student/checkpoint-19850"
param_count: "125M"
