devices: "0"
experiment_name: "codex_teacher_pass100_1B_student"
teacher_data_path: "../few_shot/results/codex_gsm8k_full_pass100.json"
lr: 2.e-5
epochs: 50
batch_size: 8
weight_decay: 0.01
model_name: "EleutherAI/gpt-neo-1.3B"
model_type: "gptneo"
max_length: 400


