batch_size: 8
devices: '0'
do_train: false
epochs: 140
eval_batch_size: 1
experiment_name: codex_teacher_pass100_gptneo1B_student_validation_pass1_standard_params_test_100
gradient_accumulation_steps: 4
lr: 0.0001
max_gen_tokens: 150
max_length: 400
model_name: EleutherAI/gpt-neo-1.3B
model_path: /home/lily/zaa7/ETK/etk/full_supervision/train_results/codex_teacher_pass100_gptneo1B_student_validation_pass1_standard_params/checkpoint-28420
model_type: gptneo
num_samples: 100
teacher_data_path: ../few_shot/results/codex_gsm8k_full_pass100.json
temp: 0.6
train_on_dev: false
weight_decay: 0.1
