batch_size: 16
devices: '1'
epochs: 140
eval_batch_size: 1
experiment_name: gptneo2B_teacher_pass100_gptneo125M_student_with_validation_new_hparams
gradient_accumulation_steps: 2
lr: 0.0001
max_gen_tokens: 150
max_length: 400
model_name: EleutherAI/gpt-neo-125M
model_type: gptneo
num_samples: 10
teacher_data_path: ../few_shot/results/gptneo2B_gsm8k_full_pass100.json
temp: 0.2
train_on_dev: false
weight_decay: 0.1
