device: '1'
experiment_name: codex_teacher_pass100_student_125M_pass10_temp0.2
inference_batch_size: 24
max_new_tokens: 200
model_name: EleutherAI/gpt-neo-125M
model_path: train_results/codex_teacher_pass100_125M_student/checkpoint-21750/
model_type: gptneo
num_samples: 10
prompt_length: 200
temp: 0.2
